version: '3.8'

services:
  sqlserver-db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Sinclave1!"
    ports:
      - 1433:1433
    volumes:
      - ./sqlserver:/var/opt/mssql
    user: "0:0"  # Ejecuta como root temporalmente para comprobar si es un problema de permisos
